/* CREACION DE TABLAS GENERAL PARA CRM*/
SELECT * FROM crm.USUARIO;

INSERT INTO crm.USUARIO(ID, USUARIO, CONTRASENIA, EMAIL, FECHA_CREACION, ESTADO)VALUES(1,'WFERNANDEZ','1234','TEST@GMAIL.COM',SYSDATE, 'ACT');