CREATE TABLE CRM.Pais(
	Id NUMBER,
	CodigoPais NUMBER,
	Descripcion VARCHAR2(30),
	CONSTRAINT PK_Pais_ID PRIMARY KEY(Id)
);

CREATE TABLE CRM.DireTipo(
	Id NUMBER,
	Descripcion VARCHAR2(30),
	CONSTRAINT PK_DireTipo_Id PRIMARY KEY(Id)
);

CREATE TABLE CRM.Estado(
	Id NUMBER,
	Descripcion VARCHAR2(30),
	IdPais NUMBER,
	CONSTRAINT PK_Estado_Id PRIMARY KEY(Id),
	CONSTRAINT CRM_Pais_FK_R_Estado FOREIGN KEY(IdPais) REFERENCES CRM.Pais(Id)
);

CREATE TABLE CRM.Provincia(
	Id NUMBER,
	Descripcion VARCHAR2(30),
	CodifoProvincia NUMBER,
	IdEstado NUMBER,
	CONSTRAINT PK_Provincia_Id PRIMARY KEY(Id),
	CONSTRAINT CRM_Estado_FK_R_Provincia FOREIGN KEY(IdEstado) REFERENCES CRM.Estado(Id)
);

CREATE TABLE CRM.Area(
	Id NUMBER,
	Descripcion VARCHAR2(30),
	CodigoArea NUMBER,
	IdProvincia NUMBER,
	CONSTRAINT PK_Area_Id PRIMARY KEY(Id),
	CONSTRAINT CRM_Provincia_FK_R_Area FOREIGN KEY(IdProvincia) REFERENCES CRM.Provincia(Id)
);

CREATE TABLE CRM.Direccion( 
	Id NUMBER,
	Descripcion VARCHAR2(30),
	IdCliente NUMBER,
	IdProvincia NUMBER,IdArea NUMBER,
	IdTipoDireccion NUMBER,
	IdDireTipo NUMBER,
	CONSTRAINT PK_Direccion_Id PRIMARY KEY (Id), 
	CONSTRAINT CRM_Provincia_FK_R_Direccion FOREIGN KEY(IdProvincia) REFERENCES CRM.Provincia(Id),
	CONSTRAINT CRM_Area_FK_R_Direccion FOREIGN KEY(IdArea) REFERENCES CRM.Area(Id), 
	CONSTRAINT CRM_Cliente_FK_R_Direccion FOREIGN KEY(IdCliente) REFERENCES CRM.Clientes(Id), 
	CONSTRAINT CRM_DireTipo_FK_R_Direccion FOREIGN KEY (IdDireTipo) REFERENCES CRM.DIRETIPO (Id) 
);

CREATE SEQUENCE CRM.DireTipoSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.PaisSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.EstadoSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.ProvinciaSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.AreaSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.DireccionSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

