CREATE TABLE CRM.TiposProdu(
	Id NUMBER,
	Descripcion VARCHAR2(50),
	CONSTRAINT PK_TiposProdu_Id PRIMARY KEY(Id)
);

CREATE TABLE CRM.TiposPresus(
	Id NUMBER,
	Descripcion VARCHAR2(50),
	CONSTRAINT PK_TiposPresu_Id PRIMARY KEY(Id)
);

CREATE TABLE CRM.Campania(
	Id NUMBER,
	Descripcion VARCHAR2(50),
	CONSTRAINT PK_Campania_Id PRIMARY KEY(Id)
);

CREATE TABLE CRM.Productos(
	Id NUMBER,
	Descripcion VARCHAR2(50),
	IdTiposProdu NUMBER,
	CONSTRAINT PK_Productos_ID PRIMARY KEY(Id),
	CONSTRAINT CRM_TiposProdu_FK_R_Prosuctos FOREIGN KEY(IdTiposProdu) REFERENCES CRM.TiposProdu(Id)
);

CREATE TABLE CRM.Presupuestos( 
	Id NUMBER,
	FechaDesde DATE,
	FechaHasta DATE,
	IdTiposProdu NUMBER,
	IdTiposPresu NUMBER,
	CONSTRAINT PK_Presupuestos_Id PRIMARY KEY(Id),
	CONSTRAINT CRM_Tipos_FK_R_Presupuestos FOREIGN KEY(IdTiposPresu) REFERENCES CRM.TIPOSPRESUS(Id),
	CONSTRAINT CRM_TiposProdu_FK_R_Productos FOREIGN KEY(IdTiposProdu) REFERENCES CRM.PRODUCTOS(Id)
);

CREATE TABLE CRM.PresusDetalles(
	Id NUMBER,
	Mes DATE,
	Anio DATE,
	Unidades NUMBER,
	Monto VARCHAR2(10),
	IdPresupuestos NUMBER,
	IdProductos NUMBER,
	CONSTRAINT PK_PresusDetalles_Id PRIMARY KEY(Id),
	CONSTRAINT CRM_Presu_FK_R_PresusDetalles FOREIGN KEY(IdPresupuestos) REFERENCES CRM.Presupuestos(Id),
	CONSTRAINT CRM_Productos_FK_R_Productos FOREIGN KEY(IdProductos) REFERENCES CRM.PRODUCTOS(Id)
);

CREATE TABLE CRM.CampaPresu(
	IdPresupuesto NUMBER,
	IdCampania NUMBER,
	Descripcion VARCHAR2(50),
	CONSTRAINT CRM_Presu_FK_R_CampaPresu FOREIGN KEY(IdPresupuesto) REFERENCES CRM.Presupuestos(Id),
	CONSTRAINT CRM_Campanias_FK_R_CampaPresu FOREIGN KEY (IdCampania) REFERENCES CRM.CAMPANIA(Id)
);

CREATE SEQUENCE CRM.TiposProduSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.TiposPresusSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.CampaniaSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.ProductosSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.PresupuestoaSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.PresusDetallesSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;

CREATE SEQUENCE CRM.CampaPresuSqu
INCREMENT BY 1
 START WITH 1
NOMAXVALUE;