
/*CREACION DEL ESQUEMA PARA CRM*/


CREATE USER CRM IDENTIFIED BY CRM DEFAULT TABLESPACE USERS;

GRANT CONNECT TO CRM;

GRANT RESOURCE TO CRM;

GRANT ALL PRIVILEGES TO CRM;


/***************************/